# LANRails settings and defaults

site_title:
  default: LANRails
 
require_newacct_activation:
  default: true

email_from:
  default: noreply@example.com

frontpage_news_limit:
  default: 5

site_theme:
  default: default
