# LANRails settings and defaults
# how they are displayed here, top down is how they will display in the
# site_settings page

site_title:
  default: LANRails
  friendly: Site Title

site_theme:
  default: lanrails
  friendly: Site Theme
  type: theme_picker

require_newacct_activation:
  default: false
  friendly: Require Account Activation
  type: boolean

enable_recaptcha:
  default: false
  friendly: Enable reCaptcha
  type: boolean

recaptcha_public:
  default: 6Le2BAQAAAAAAAqblFVvt6bxirIW-c9PXyC9VLTm
  friendly: reCaptcha Public Key

recaptcha_private:
  default: 6Le2BAQAAAAAAMJrxlnxsXbrJB7Cp-wCixhRJLSm
  friendly: reCaptcha Private Key

email_from:
  default: noreply@example.com
  friendly: Send Mail As

frontpage_news_limit:
  default: 5
  friendly: News On Front Page

enable_paypal:
  default: true
  friendly: Enable PayPal
  type: boolean

paypal_address:
  default: paypal@example.com
  friendly: PayPal Email

enable_forums:
  default: true
  friendly: Enable Forums
  type: boolean

enable_tournaments:
  default: true
  friendly: Enable Tournaments
  type: boolean
