# LANRails settings and defaults

site_title:
  default: LANRails
 
require_newacct_activation:
  default: false

email_from:
  default: noreply@example.com

frontpage_news_limit:
  default: 5

site_theme:
  default: default

paypal_address:
  default: paypal@example.com